import '../styles/globals.css'
import { ReactNode } from 'react'
import Nav from '../components/Nav'

export const metadata = {
  title: 'Mrcto Marketing',
  description: 'Generated by codex agent',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 font-sans text-gray-800 antialiased">
        <Nav />
        {children}
      </body>
    </html>
  )
}
