import '../styles/globals.css'
import { ReactNode } from 'react'
import Nav from '../components/Nav'
import SlackChatButton from '../components/SlackChatButton'

export const metadata = {
  title: 'Mrcto Marketing',
  description: 'Generated by codex agent',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-100 text-gray-800">
        <Nav />
        {children}
        <SlackChatButton />
      </body>
    </html>
  )
}
